### ISSUE TITLE
Attribution to original project?

### ISSUE THREAD

**Issue by juliardi** [MedanSoftware/C45-Algorithm-PHP#3]
Hello, I am the author of https://github.com/juliardi/C45, a PHP implementation of C4.5 algoritm, which I believe is the base project for this repository. Now, I see that you have modified and redistribute the code, and the MIT License which I have attached to my project indeed permitted it. But, MIT License gave a condition to the redistribution, that is to also include the original copy of the license which included the original author name. So, can I ask you to include the original license and attribution to the original project?

**Comment by agoenks29D** [comment]
Sure, i have do it. I am say sorry about the project author & license.
But i have write reference from your repository at the bottom of Readme.md

**Comment by juliardi** [comment]
Thanks, I appreciate that
